---
- name: Installing and Launch metricbeat
  hosts: webservers
  become: yes
  tasks:
    # Use command module
  - name: Download metricbeat .rpm file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-x86_64.rpm
    # Use command module
  - name: Install metricbeat .rpm
    command: sudo rpm -vi metricbeat-7.6.1-x86_64.rpm
    # Use copy module
  - name: Drop in filebeat.yml
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
    # Use command module
  - name: Enable and Configure System Module
    command: sudo metricbeat modules enable docker
    # Use command module
  - name:  metricbeat setup
    command: sudo metricbeat setup
    # Use command module
  - name: Start metricbeat service
    command: sudo service metricbeat start
    # Use systemd module
  - name: Enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes
